name: Run TaskManagement.Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Update if you're using a different version

      - name: Restore test project dependencies
        run: dotnet restore TaskManagement.Tests/TaskManagement.Tests.csproj

      - name: Build test project
        run: dotnet build TaskManagement.Tests/TaskManagement.Tests.csproj --no-restore

      - name: Run tests and generate .trx report
        run: |
          mkdir -p TestResults
          dotnet test TaskManagement.Tests/TaskManagement.Tests.csproj \
            --no-build \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults
