name: Run Tests for TaskManagement.Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests for TaskManagement.Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Adjust to your .NET version if different

    - name: Restore Dependencies
      run: dotnet restore src/API/TaskManagement.Test/TaskManagement.Tests.csproj

    - name: Build Solution
      run: dotnet build src/API/TaskManagement.Test/TaskManagement.Tests.csproj --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test src/API/TaskManagement.Test/TaskManagement.Tests.csproj --no-build --configuration Release --verbosity normal
